<a href="https://colab.research.google.com/github/IsidroJ/Colab_Archivos_Clase_PADP/blob/main/Practica_4_Manipulaci%C3%B3n_de_matrices_IJGH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practica 4. Manipulación de matrices**

Crear dos matrices de 3x3 con números aleatorios entre 1 y 10. Realizar las siguientes operaciones:

1. Suma ambas matrices.
2. Resta la segunda matriz de la primera.
3. Multiplica la primera matriz por 2.
4. Realiza una multiplicación matricial entre las dos matrices.

# **Creación de dos matrices de 3x3**

Cargar la librería NumPy

In [12]:
import numpy as np

MatrizA = np.random.randint(1, 10, (3, 3))
MatrizB = np.random.randint(1, 10, (3, 3))
print("Matriz A:\n", MatrizA)

print('\n')

print("Matriz B:\n", MatrizB)

Matriz A:
 [[6 4 3]
 [2 6 5]
 [9 6 6]]


Matriz B:
 [[8 1 1]
 [3 4 6]
 [8 1 8]]


# **1. Suma ambas matrices.**
La suma de matrices en matemáticas significa sumar elemento a elemento de dos matrices de igual tamaño. Es decir, mismas dimensiones (mismo número de filas y columnas).

In [17]:
SumaMatriz = np.array(MatrizA) + np.array(MatrizB)
print(f"La suma de las matrices es:\n {SumaMatriz}")


La suma de las matrices es:
 [[14  5  4]
 [ 5 10 11]
 [17  7 14]]


# **2. Resta la segunda matriz de la primera.**
La resta de matrices funciona igual que la suma, pero restando cada elemento correspondiente.

In [18]:
SumaMatriz = np.array(MatrizA) - np.array(MatrizB)
print(f"La suma de las matrices es:\n {SumaMatriz}")


La suma de las matrices es:
 [[-2  3  2]
 [-1  2 -1]
 [ 1  5 -2]]


# **3. Multiplica la primera matriz por 2.**
Multiplicar una matriz por un número (en este caso un escalar) significa multiplicar cada elemento de la matriz por ese número o escalar.

In [19]:
EscalarMatriz = np.array(MatrizA)*2
print(f"La multiplicaciónd e la matriz por el 2(escalar) es:\n {EscalarMatriz}")

La multiplicaciónd e la matriz por el 2(escalar) es:
 [[12  8  6]
 [ 4 12 10]
 [18 12 12]]


# **4. Realiza una multiplicación matricial entre las dos matrices.**
La multiplicación de dos matrices no es igual a la suma, ni a la resta, ni a la multiplicación por un número(escalar). Aquí se realiza un producto matricial.




In [25]:
print("MatrizA:\n", A)
print('\n')

print("Matriz B:\n", B)
print('\n')

print("Multiplicación matricial:\n", np.dot(MatrizA, MatrizB))

MatrizA:
 [[6 5 8]
 [5 2 6]
 [5 2 4]]


Matriz B:
 [[5 9 8]
 [7 4 5]
 [2 5 1]]


Multiplicación matricial:
 [[ 84  25  54]
 [ 74  31  78]
 [138  39  93]]
