<a href="https://colab.research.google.com/github/IsidroJ/Colab_Archivos_Clase_PADP/blob/main/Practica_3_Arreglos_IJGH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practica 3. Creación de un arreglo y operaciones básicas**

Crea un arreglo unidimensional de 20 elementos con valores aleatorios entre 1 y 100. Luego, realiza las siguientes operaciones:

1. Encuentra el valor máximo del arreglo.

2. Encuentra el valor mínimo del arreglo.

3. Calcula la media del arreglo.

4. Suma 10 a cada elemento del arreglo.

In [19]:
import numpy as np
arreglo = np.random.randint(1, 101, 20)
print(f"El arrego es:\n {arreglo}")


El arrego es:
 [11  5 56 57 37 50 76 72 81 28 68 33 46 17 20 19 87 61 69 11]


**1. Encuentra el valor máximo del arreglo.**

In [20]:
valor_max = np.max(arreglo)
print(f"El valor máximo del arrego es: {valor_max}")


El valor máximo del arrego es: 87


**2. Encuentra el valor mínimo del arreglo.**

In [21]:
valor_min = np.min(arreglo)
print(f"El valor mínomo del arrego es: {valor_min}")


El valor mínomo del arrego es: 5


**3. Calcula la media del arreglo.**

In [22]:
promedio = np.mean(arreglo)
print(f"El valor promedio del arrego es: {promedio}")


El valor promedio del arrego es: 45.2


**4. Suma 10 a cada elemento del arreglo.**

In [23]:
EleArr5 = arreglo + 5
print(f"Arreglo origibal: \n {arreglo}")
print('\n')
print(f"Se sumaron 5 unidades a cada elemento del arrego, el nuevo arrego es: \n {EleArr5}")


Arreglo origibal: 
 [11  5 56 57 37 50 76 72 81 28 68 33 46 17 20 19 87 61 69 11]


Se sumaron 5 unidades a cada elemento del arrego, el nuevo arrego es: 
 [16 10 61 62 42 55 81 77 86 33 73 38 51 22 25 24 92 66 74 16]
